name: build-site
on:
  push:
    branches-ignore: 
      - gh-pages
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      
      - name: Install
        run: npm install
        
      - name: Build
        run: npm run build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-site
          path: dist/
      
      - name: Checkout to build
        uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
      
      - name: Create and go to branch folder if needed
        run: |
          mkdir branches/${{ github.ref_name }}
          cd branches/${{ github.ref_name }}
        if: github.action_ref != 'master'
      
      - name: Clear out assets folder
        run: rm -rf ./assets
      
      - name: Clear out index.html
        run: rm -rf ./index.html
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: built-site
          path: .
      
      - name: Commit and push
        uses: EndBug/add-and-commit@v8
        with:
          message: Build site
          push: true
